export type ShareSigilSpec = {
  intentLabel: string;
  birthYear?: number;
  ageBand?: string;
  zodiac?: string;
  titleSeed?: string;
  headlineSeed?: string;
};

export type ShareRecord = {
  shareId: string;
  createdAt: string;
  title: string;
  headline: string;
  punchline: string;
  ritualPhrase: string;
  subtext: string;
  hashtags: string[];
  ctaText: string;
  ctaHref: string;
  sigilSpec: ShareSigilSpec;
  intent?: string;
  zodiac?: string;
  language?: string;
};

export type ShareSeedInput = {
  title?: string;
  headline?: string;
  punchline?: string;
  ritualPhrase?: string;
  subtext?: string;
  intent?: string;
  zodiac?: string;
  birthYear?: number;
  ageBand?: string;
  language?: string;
};

export type ShareMessageModel = {
  shareTitle: string;
  shareTextLines: string[];
  openSealPrefix: string;
};

export type ShareModel = {
  shareId: string;
  title: string;
  posterTitle: string;
  siteHost: string;
  sharedUrl: string;
  intentLine: string;
  headline: string;
  punchline: string;
  ritualPhrase: string;
  subtext: string;
  hashtags: string[];
  revealCtaText: string;
  revealCtaHref: string;
  onlineCtaLabel: string;
  sharedPath: string;
  shareTitle: string;
  shareTextLines: string[];
  sealLinkLines: string[];
  saveHint: string;
  copySuccessMessage: string;
  saveSealPosterSuccessMessage: string;
  saveRitualCardSuccessMessage: string;
  saveFailureMessage: string;
  shareFailureMessage: string;
  rewardHint: string;
  privacyNotice: string;
  posterEyebrow: string;
  readingEyebrow: string;
  blessingLabel: string;
  onlineCtaDescription: string;
  sharedLinkLabel: string;
  sealPosterLabel: string;
  sealPosterDescription: string;
  ritualCardLabel: string;
  ritualCardDescription: string;
  preserveLabel: string;
  privacyBoundaryLabel: string;
  returnOfLightLabel: string;
  saveSealPosterLabel: string;
  saveRitualCardLabel: string;
  hdExportLabel: string;
  savingSealPosterLabel: string;
  savingRitualCardLabel: string;
  copySealLinkLabel: string;
  copyingSealLinkLabel: string;
  saveSealPosterDetail: string;
  saveRitualCardDetail: string;
  saveFailureDetail: string;
  copySuccessDetail: string;
  copyFallbackDetail: string;
  energyRewardMessage: string;
  openSealPrefix: string;
  language: string;
  sigilIntent: string;
  sigilSpec: ShareSigilSpec;
  qrSvg: string;
};
